### ISSUE TITLE
Do we need support for a configurable autodiscovery.lock location?

### ISSUE THREAD

**Issue by silvano-a** [goedemiddag/laravel-autodiscovery-lock#10]

**Comment by dvdheiden** [comment]
We could easily do that by adding a config file with a sane default. Users of the package are able to publish the config file if they want to change the location. I can create a PR for you if you agree.

**Comment by silvano-a** [comment]
@dvdheiden that sounds great! I've created issue #23 for that.

**Comment by silvano-a** [comment]
will be implemented in #23
